@API_HostAddress = https://localhost:7246
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJZCI6IjkwMDMiLCJuYW1lIjoiSm9obiBEb2UiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3Nzg3MTU4NzAsImV4cCI6MTc3ODcxOTQ3MCwiaWF0IjoxNzc4NzE1ODcwfQ.M80MDWClWMYQ4sGLxaI-Zb2a7S0VUO3eFwmZ7_Yqpro

###

POST {{API_HostAddress}}/api/slot/spin
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
   "bet": 50
}

###