@API_HostAddress = https://localhost:7246
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJZCI6IjI3IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNzc4Njc3MTMwLCJleHAiOjE3Nzg2ODA3MzAsImlhdCI6MTc3ODY3NzEzMH0.tvWNb9p3pWSeYY5klijMmLy98wIs8DIwmcfZ95VpNxY

###

POST {{API_HostAddress}}/api/slot/spin
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
   "bet": 50
}

###
